Lint and Black for code

diff --git a/.github/workflows/django.yml b/.github/workflows/django.yml
--- a/.github/workflows/django.yml
+++ b/.github/workflows/django.yml
@@ -26,9 +26,36 @@ jobs:
       run: |
         python -m pip install --upgrade pip
         pip install -r ./requirements.txt
-    - name: Run Tests'
-      if: success() || failure()
-      env:
-        SECRET_KEY: ''
+        - name: Lint with flake8
       run: |
-        python manage.py test
+        pip install flake8
+        # stop the build if there are Python syntax errors or undefined names
+        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
+        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
+    - name: Lint with pylint
+      run: |
+        pip install pylint
+        pylint .
+    - name: Lint with black
+      run: |
+        pip install black
+        black .
+    - name: Lint with isort
+      run: |
+        pip install isort
+        isort .
+    - name: Lint with pycodestyle
+      run: |
+        pip install pycodestyle
+        pycodestyle .
+    - name: Lint with mypy
+      run: |
+        pip install mypy
+        mypy .
+    # - name: Run Tests'
+    #   if: success() || failure()
+    #   env:
+    #     SECRET_KEY: ''
+    #   run: |
+    #     python manage.py test
